services:
  eduskillhubfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-js-eduskillhub:learning
    container_name: eduskillhub-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
